#!/usr/bin/env bash

# If boom site is not set, don't even source
[[ -n "$GS_URL" && "$BOOMSITE" =~ ^"$GS_URL" ]] || return 1

_boomActionCache=/tmp/testing

# This is how we tell what command we are on (and why we need bash 4.4+)
readonly BOOM_MAGICPROMPT='\#' &>/dev/null

# Starts at -1 to preserve legacy (pre offline-2.2.9) "feature" of booming on terminal start
BOOMPREV_CMDNO=-1
BOOMPREV_HISTCMD=$HISTCMD # int currrent cmd num in history

__gs_unset_vars_from_prefixes _BE_

# Set default emojis
_BE_BOOM_DEF="💥"
_BE_HOLE_DEF="🕳️"
_BE_BOT_DEF="🤖"
_BE_SUPER_DEF="⚡️"
_BE_HOG_DEF="🐷"
_BE_IMPORT_DEF="⬇️"
_BE_EXPORT_DEF="⬆️"
_BE_CHECK_DEF="✅"

# Overwrite defaults with custom if defined
_BE_BOOM="${BOOM_EMOJI:-$_BE_BOOM_DEF}"
_BE_HOLE="${HOLE_EMOJI:-$_BE_HOLE_DEF}"
_BE_BOT="${BOT_EMOJI:-$_BE_BOT_DEF}"
_BE_SUPER="${SUPER_EMOJI:-$_BE_SUPER_DEF}"
_BE_HOG="${HOG_EMOJI:-$_BE_HOG_DEF}"
_BE_IMPORT="${IMPORT_EMOJI:-$_BE_IMPORT_DEF}"
_BE_EXPORT="${EXPORT_EMOJI:-$_BE_EXPORT_DEF}"
_BE_CHECK="${CHECK_EMOJI:-$_BE_CHECK_DEF}"

__goodEmoji() {
  # Really just making sure emojis aren't terrible chars
  local s="$1"
  local exitCode=0

  # Reject empty just in case
  [[ -z "$s" ]] && exitCode=1

  # Reject any whitespace
  [[ "$s" == *[[:space:]]* ]] && exitCode=2

  # Reject any ASCII control characters
  LC_ALL=C printf '%s' "$s" | grep -q '[[:cntrl:]]' && exitCode=3

  # Reject shell metacharacters
  [[ "$s" == *[\`\"\'\\\$]* ]] && exitCode=4

  # Reject long strings
  (( ${#s} >= 3 )) && exitCode=5

  if (( exitCode != 0 )); then
    __gs_errormsg "$s is an invalid emoji, ignoring with exit code $exitCode..."
  fi

  return $exitCode
}

# Reset to defaults if bad
__goodEmoji "$_BE_BOOM" || _BE_BOOM="$_BE_BOOM_DEF"
__goodEmoji "$_BE_HOLE" || _BE_HOLE="$_BE_HOLE_DEF"
__goodEmoji "$_BE_BOT" || _BE_BOT="$_BE_BOT_DEF"
__goodEmoji "$_BE_SUPER" || _BE_SUPER="$_BE_SUPER_DEF"
__goodEmoji "$_BE_HOG" || _BE_HOG="$_BE_HOG_DEF"
__goodEmoji "$_BE_IMPORT" || _BE_IMPORT="$_BE_IMPORT_DEF"
__goodEmoji "$_BE_EXPORT" || _BE_EXPORT="$_BE_EXPORT_DEF"
__goodEmoji "$_BE_CHECK" || _BE_CHECK="$_BE_CHECK_DEF"
unset -f __goodEmoji

__boomcmdno() {
  export $1=$(printf '%s' "${BOOM_MAGICPROMPT@P}")
}

__boomvar() {
  local action="$1" var="$2"
  case _${action}_ in
    _activate_)
      export $var="yes"
    ;;
    _active_)
      [[ "${!var}" == "yes" ]]
      return
    ;;
    _inactive_)
      [[ "${!var}" != "yes" ]]
      return
    ;;
  esac
}

__doom() {
  local action="$1"
  case _${action}_ in
    _127_)
      if __doom active; then
        echo bash: ${FUNCNAME[-1]}: command not found
        return 127
      fi
      return 0
    ;;
    _activate_) ;&
    _active_) ;&
    _inactive_)
      __boomvar $action DOOMBOOM
      return
    ;;
    #_file-access_)
    #  [[ ! -w "$2" ]] && __boomvar activate DOOMBOOM
    #;;
    #_persist_)
    #  if [[ -w "$_doomTracker" ]] && __doom tracker-oos; then
    #    if [[ "$(cat $_doomTracker 2>/dev/null)" =~ "yes" ]]; then
    #      clear
    #    else
    #      export AUTOBOOMBOT=
    #      echo $_BE_BOOM$_BE_BOOM WE BRING THE BOOM $_BE_BOOM$_BE_BOOM
    #    fi
    #    DOOMBOOM=$(cat $_doomTracker)
    #  fi
    #;;
    #_tracker-oos_)
    #  # Is the tracker out of state?
    #  [[ "$(cat $_doomTracker 2>/dev/null)" != "$DOOMBOOM" ]]
    #  return
    #;;
  esac
}

bang() {
  __doom 127 || return
  local i
  for (( i=0; i<${1:-1}; i++ )); do echo -n ${_BE_BOOM}; done; echo
}

__boom_action() {
  local action args trash
  local cmd ranking
  local line

  read -r action args <<<"$@"
  case _${action}_ in
    _RANK_)
      read -r cmd ranking trash <<<"$args"
      __gs_required_args -q cmd ranking && line="$action $cmd $ranking"
    ;;
    _CHATLOG_) ;&
    _BOOMLOG_)
      local phrase="$args"
      __gs_required_args -q phrase && line="$action $phrase"
    ;;
  esac
  local now=${EPOCHSECONDS:-$(date +%s)}
  [[ -n "$line" ]] && echo "$now $line" >> $_boomActionCache
}

__boommeter() {
  # This magic skips empty lines
  __boomcmdno BOOM_CMDNO
  if (( BOOM_CMDNO == BOOMPREV_CMDNO )); then return; fi

  local cmd=$(fc -ln -1 | head -n 1 | awk '{print $1}')
  local cmd="${cmd//\\}"

  if [[ -n "$cmd" ]]; then
    local odds=15
    if (( RANDOM % odds == 7 )); then
      __boommeter_roll "$cmd" _log_
    fi
  fi

  BOOMPREV_HISTCMD=$HISTCMD
  BOOMPREV_CMDNO=$BOOM_CMDNO
}

__boommeter_roll() {
  local cmd="$1"
  local runner="$2"

  local prefix="Let's rank it on the boom meter! "
  case _${runner}_ in
    __log__)
      [[ "$cmd" =~ [!./[\"\']+ ]] && return
      prefix="Random boom meter! "
    ;;
    __bot__) prefix="BoomBot thinks " ;;
  esac

  local score=$(( RANDOM % 8 + 1 ))
  (( score > 5 )) && score=5
  (( RANDOM % 500 == 365 )) && score=6

  local plural=""
  (( score > 1 )) && plural="s"

  local emojis="$(bang $score)"
  local suffix="gets $score big boom${plural}! $emojis"

  case _${runner}_ in
    __bot__)
      __boom_action CHATLOG "${prefix}$cmd ${suffix/gets/is}"
    ;;
    __cmd__)
      echo "${prefix}$cmd $suffix"
      prefix="$GS_USER is ranking it on the boom meter! "
      __boom_action CHATLOG "${prefix}$cmd $suffix"
    ;;
    __log__)
      echo "${prefix}$cmd $suffix"
      __boomlog "$cmd" "$score"
    ;;
  esac
}
__boomlog() {
  local cmd="$1" score="$2" host="$3"
  local plural=""
  (( score > 1 )) && plural="s"

  # Log boom event to site
  __boom_action BOOMLOG "$GS_USER boomed $cmd for $score boom${plural}${host:+ on $host}!"

  # Log ranking if no problematic chars
  [[ "$1" =~ ^[^!/.[\"\']+$ ]] && __boom_action RANK "$cmd" "$score"
}

boommeter() {
  __doom 127 || return
  local phrase="$*"
  if [[ -n "$phrase" ]]; then
    __boommeter_roll "$phrase" _cmd_
  else
    echo "Give us something to rank on the boom meter!"
  fi
}

