#!/usr/bin/env bash

# If boom site is not set, don't even source
[[ -n "$GS_URL" && "$BOOMSITE" =~ ^"$GS_URL" ]] || return 1

__BOOM_IMPORTS=(
  static/{vars,action,drought,meter,hall}
)

for import in ${__BOOM_IMPORTS[@]}; do
  __gs_source_file $import boom
done
unset import __BOOM_IMPORTS

